import math

from lib.constants import C_AIR

# ROOM SIZE
WIDTH = 3.6
DEPTH = 4.3
HEIGHT = 2.4

# SIMULATION
MAX_FREQUENCY = 2000
AIR_DAMPENING = 1

# --------- CALCULATED ---------
MIN_WAVELENGTH = C_AIR / MAX_FREQUENCY
DELTA_SPACE = DX = MIN_WAVELENGTH / 16 # 16 is slightly arbitrary
DELTA_TIME = DT = DX / (math.sqrt(3) * C_AIR) # 3 => 3D
DT_OVER_DX = DT / DX

# CALCULATED
WIDTH_PARTS = math.floor(WIDTH / DX) + 1
HEIGHT_PARTS = math.floor(HEIGHT / DX) + 1
DEPTH_PARTS = math.floor(DEPTH / DX) + 1
GRID_SIZE = WIDTH_PARTS * HEIGHT_PARTS * DEPTH_PARTS
GRID_SHAPE = (WIDTH_PARTS, HEIGHT_PARTS, DEPTH_PARTS)
